repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5  # use latest stable version if newer
    hooks:
      - id: ruff
        args: [--fix]

      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true